twist_mux:
  ros__parameters:
    topics:
      # Priorité maximale : Sécurité
      safety:
        topic:   "cmd_vel_safety"
        timeout: 0.5
        priority: 100
      # Priorité moyenne : Actions spécifiques (Pousser des objets)
      push:
        topic:   "cmd_vel_push"
        timeout: 0.5
        priority: 50
      # Priorité basse : Navigation standard
      navigation:
        topic:   "cmd_vel_nav"
        timeout: 0.5
        priority: 10